// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"
)

type Comment struct {
	CommentID   int32
	PostID      int32
	UserID      int32
	Message     string
	CommentLike sql.NullInt32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
